### ISSUE TITLE
Building screensaver is okey but building app fails

### ISSUE THREAD

**Issue by perez987** [st235/RainingCode#1]
Hello, Alex, I like very much this nice project, really nice to be seen in action.
I'm in Monterey and Xcode 13.
Project builds without error (only a warning about ambiguous width of Color Well) but I only get the screensaver (it runs fine). The macOS app product never exists and it remains in red in Xcode workspace.
Do you know how to fix this?
Thanks for your work.

**Comment by st235** [comment]
Hey,

thank you for showing interest in the project. Don't know what can be an issue but give me some time and I will check it for you.

Best regards,
Alex

**Comment by perez987** [comment]
Thanks!!!

**Comment by st235** [comment]
Have you changed the build target at the targets dropdown?

<img width="686" alt="Screenshot 2021-11-28 at 06 52 37" src="https://user-images.githubusercontent.com/14966197/143732672-53e06701-5abc-4522-9ef2-491e319708ae.png">

For me it seems like it is working just fine,

<img width="1392" alt="Screenshot 2021-11-28 at 06 53 24" src="https://user-images.githubusercontent.com/14966197/143732686-ac35288a-04d5-4f64-99f8-34f1a7bdd7b6.png">
 
Best wishes,
Alex

**Comment by perez987** [comment]
Wait, I'm not at home, I'll tell you later. Thanks.

**Comment by st235** [comment]
@perez987 any updates?

**Comment by perez987** [comment]
@st235 
Sorry for the delay.
Yes, it was the build target at the targets dropdown, my mistake.
Now it's building fine. Screensaver and app.
Thanks for your help.
I would like to add a way to quit the app from keyboard or menu without clicking Quit on the Dock icon. But this is another different thing.
Congratulations, I think this is a very demonstrative code for beginners like me.

**Comment by st235** [comment]
Oh, no problems at all. Thank you very much for checking this for me.
Then I will close the issue.
Good luck in your future endeavors and do not hesitate to contact!
